#Docs: https://docs.docker.com/compose/compose-file 

version: "3.3"
services:

  #------ Client Container ------#
  client:
    container_name: my-react-nginx-client
    image: inbarprojects/my-react-nginx-client:latest
    pull_policy: always

    ports:
      - 80:80
      - 443:443

    #Vars in default server's env file, Accesible via Node's global varaiable - process.env.VAR_NAME
    env_file:
      - .env
    environment:
      - NODE_ENV=${env}

    stdin_open: true #Keep STDIN open even if not attached, Same as docker run --interactive 
    tty: true #Allocate a pseudo-TTY, Same as docker run --tty   
