##--------------------- React client image ---------------------#

#Build react client
FROM node:latest AS builder

#Set working directory inside the container
WORKDIR /usr/share/nginx/html/

#Copy files from project's directory to working directory in container
COPY app/client .

#Packages setup
RUN npm config set fund false 
RUN npm install
RUN npm run build

#--------------------- Nginx web server ---------------------#

#Buid nginx web service
FROM nginx:latest

#Set working directory inside the container
WORKDIR /usr/share/nginx/html/

#Remove default nginx static assets
RUN rm -rf /usr/share/nginx/html/*

#Copy static assets from built app
# COPY --from=builder /app/client/build /usr/share/nginx/html/
# COPY --from=builder /app/client/build /usr/share/nginx/html/

#Containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]
