name: Backend Build and Deploy

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Image
        run: docker build --file ./docker/dockerfile-server --tag ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_SERVER_REPO }}:latest .

      - name: Push to DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_SERVER_REPO }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_BACKEND }}
          username: ${{ secrets.HOST_BACKEND_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            sudo docker stop ${{ secrets.DOCKER_SERVER_CONTAINER }}
            sudo docker rm ${{ secrets.DOCKER_SERVER_CONTAINER }}
            sudo docker rmi ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_SERVER_REPO }}
            sudo docker pull ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_SERVER_REPO }}
            sudo docker compose --file /opt/${{ secrets.APP_NAME }}/docker/docker-compose-server.yml --project-directory /opt/${{ secrets.APP_NAME }} up server -d
