name: Frontend Build and Deply

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create env file and add api url
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_API: "http://{{ secrets.HOST_BACKEND }}"
          directory: app/client
          file_name: .env
          fail_on_empty: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Image
        run: docker build --file docker/dockerfile-client --tag ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_CLIENT_REPO }}:latest .

      - name: Push to DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_CLIENT_REPO }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_FRONTEND }}
          username: ${{ secrets.HOST_FRONTEND_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            sudo docker stop ${{ secrets.DOCKER_CLIENT_CONTAINER }}
            sudo docker rm ${{ secrets.DOCKER_CLIENT_CONTAINER }}
            sudo docker rmi ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_CLIENT_REPO }}
            sudo docker pull ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_CLIENT_REPO }}

      - uses: isbang/compose-action@v1.1.0
        with:
          compose-file: "./docker/docker-compose-client.yml"
          up-flags: "--detach"
